hadd -f UL16_postprocessing/combined/MC13TeV_TTJets_SL.root UL16_postprocessing/MC13TeV_TTJets_SL_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_TTJets_AH.root UL16_postprocessing/MC13TeV_TTJets_AH_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_TTJets_DL.root UL16_postprocessing/MC13TeV_TTJets_DL_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_DY_M-50-MG.root UL16_postprocessing/MC13TeV_DY_M-50-MG_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_WW.root UL16_postprocessing/MC13TeV_WW_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_WZ.root UL16_postprocessing/MC13TeV_WZ_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_ZZ.root UL16_postprocessing/MC13TeV_ZZ_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_atW_noFullHad.root UL16_postprocessing/MC13TeV_atW_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_tW_noFullHad.root UL16_postprocessing/MC13TeV_tW_*.root
hadd -f UL16_postprocessing/combined/MC13TeV_WJetsToLNu.root UL16_postprocessing/MC13TeV_WJetsToLNu_*.root
hadd -f UL16_postprocessing/combined/DataUL16.root UL16_postprocessing/crab_*.root
