#for dir in MC13TeV_TTJets_AH_erdON_HIPM/ MC13TeV_TTJets_AH_hdampDOWN_HIPM/ MC13TeV_TTJets_AH_hdampUP_HIPM/ MC13TeV_TTJets_AH_mtop171p5_HIPM/ MC13TeV_TTJets_AH_mtop173p5_HIPM/ MC13TeV_TTJets_AH_TuneCP5down_HIPM/ MC13TeV_TTJets_AH_TuneCP5up_HIPM/ MC13TeV_TTJets_DL_erdON_HIPM/ MC13TeV_TTJets_DL_hdampDOWN_HIPM/ MC13TeV_TTJets_DL_hdampUP_HIPM/ MC13TeV_TTJets_DL_mtop171p5_HIPM/ MC13TeV_TTJets_DL_mtop173p5_HIPM/ MC13TeV_TTJets_DL_TuneCP5down_HIPM/ MC13TeV_TTJets_DL_TuneCP5up_HIPM/ MC13TeV_TTJets_SL_erdON_HIPM/ MC13TeV_TTJets_SL_hdampDOWN_HIPM/ MC13TeV_TTJets_SL_hdampUP_HIPM/ MC13TeV_TTJets_SL_mtop171p5_HIPM/ MC13TeV_TTJets_SL_mtop173p5_HIPM/ MC13TeV_TTJets_SL_TuneCP5down_HIPM/;
#for dir in MC13TeV_tW_noFullHad_HIPM/ MC13TeV_atW_noFullHad_HIPM/ MC13TeV_DY_M-10to50-MG_HIPM/ MC13TeV_DY_M-50-MG_HIPM/ MC13TeV_TTJets_AH_HIPM/ MC13TeV_TTJets_SL_HIPM/ MC13TeV_TTJets_DL_HIPM/ MC13TeV_WW_HIPM/ MC13TeV_WZ_HIPM/ MC13TeV_ZZ_HIPM/ MC13TeV_WJetsToLNu_HIPM/;

#gkole
#for dir in crab_crab_Data13TeV_MuonEG_UL18A crab_crab_Data13TeV_MuonEG_UL18B crab_crab_Data13TeV_MuonEG_UL18C crab_crab_Data13TeV_MuonEG_UL18D MC13TeV_atW MC13TeV_DYJetsToLL-M-50 MC13TeV_TTJets_AH_hdampDOWN MC13TeV_TTJets_AH_hdampUP MC13TeV_TTJets_AH_mtop171p5 MC13TeV_TTJets_AH_mtop173p5 MC13TeV_TTJets_AH_testing MC13TeV_TTJets_AH_training MC13TeV_TTJets_AH_TuneCP5down MC13TeV_TTJets_AH_TuneCP5up MC13TeV_TTJets_DL_hdampDOWN MC13TeV_TTJets_DL_hdampUP MC13TeV_TTJets_DL_mtop171p5 MC13TeV_TTJets_DL_mtop173p5 MC13TeV_TTJets_DL_testing MC13TeV_TTJets_DL_training MC13TeV_TTJets_DL_TuneCP5down MC13TeV_TTJets_DL_TuneCP5up MC13TeV_TTJets_SL_hdampDOWN MC13TeV_TTJets_SL_hdampUP MC13TeV_TTJets_SL_mtop171p5 MC13TeV_TTJets_SL_mtop173p5 MC13TeV_TTJets_SL_testing MC13TeV_TTJets_SL_training MC13TeV_TTJets_SL_TuneCP5down MC13TeV_TTJets_SL_TuneCP5up MC13TeV_tW MC13TeV_WJetsToLNu MC13TeV_WW MC13TeV_WZ MC13TeV_ZZ
for dir in MC13TeV_TTJets_SL_TuneCP5up
    do
        echo $dir
        # Post VFP pileup (files without 'HIPM')
        #python runPileupEstimation.py --certJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt --mcDirs=/eos/cms/store/group/phys_btag/Commissioning/TTbar/TTbar_UL16_StructuredDir/${dir} --dataRange=2016 --MCName=${dir} --puJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/PileUp/UltraLegacy/pileup_latest_postVFP.txt
        # Pre VFP pileup (files with 'HIPM')
        # python runPileupEstimation.py --certJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt --mcDirs=/eos/cms/store/group/phys_btag/Commissioning/TTbar/TTbar_UL16_StructuredDir_v3/${dir} --dataRange=2016 --MCName=${dir} --puJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/PileUp/UltraLegacy/pileup_latest_preVFP.txt
        #python runPileupEstimation.py --certJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions17/13TeV/Legacy_2017/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.txt --mcDirs=/eos/cms/store/group/phys_btag/Commissioning/TTbar/TTbar_UL17_StructuredDir/${dir} --dataRange=2017 --MCName=${dir} --puJson=
        python runPileupEstimation.py --certJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt --mcDirs=/eos/cms/store/group/phys_btag/Commissioning/TTbar/TTbar_UL18_StructuredDir/${dir} --dataRange=2018 --MCName=${dir} --puJson=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/pileup_latest.txt
    done
